# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/parameter_server.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/parameter_server.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cproto/parameter_server.proto\x12\x0fparameterserver\"X\n\x0fGradientRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x0c\n\x04step\x18\x02 \x01(\x05\x12\x15\n\rgradient_data\x18\x03 \x01(\x0c\x12\r\n\x05shape\x18\x04 \x03(\x05\"4\n\x0eWeightResponse\x12\x13\n\x0bweight_data\x18\x01 \x01(\x0c\x12\r\n\x05shape\x18\x02 \x03(\x05\x32g\n\x0fParameterServer\x12T\n\rPushGradients\x12 .parameterserver.GradientRequest\x1a\x1f.parameterserver.WeightResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.parameter_server_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GRADIENTREQUEST']._serialized_start=49
  _globals['_GRADIENTREQUEST']._serialized_end=137
  _globals['_WEIGHTRESPONSE']._serialized_start=139
  _globals['_WEIGHTRESPONSE']._serialized_end=191
  _globals['_PARAMETERSERVER']._serialized_start=193
  _globals['_PARAMETERSERVER']._serialized_end=296
# @@protoc_insertion_point(module_scope)
